name: Run All Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    container: adiharif/graphir-dep

    steps:
      - uses: actions/checkout@v4

      - name: Install Git Dependencies
        run: git submodule update --init --recursive

      - name: Install NPM Packages
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Run Tests
        run: npm test

      - name: Install Python Dependencies
        run: pip install pandas matplotlib --break-system-packages

      - name: Generate Benchmarks Column Chart
        run: python3 scripts/benchmarks.py benchmarks.csv benchmarks_chart.png

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tests-results
          path: |
            jest_html_reporters.html
            benchmarks.csv
            benchmarks_chart.png
